
(function (window) {
    'use strict';

    const PRODUCTS_DATA = [
        // ================= HANDBAGS =================
        {
            id: 'handbag-01',
            slug: 'classic-flap-digital-concept',
            title: 'Classic Flap — Digital Concept',
            category: 'handbags',
            categoryLabel: 'Handbags',
            conceptTag: 'DIGITAL CONCEPT',
            demoPrice: 8900,
            primaryImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=85',
            description: 'A study in architectural proportion and timeless geometry. Crafted with diamond-quilted calfskin leather, double-interlocking clasp concept, and braided chain shoulder strap in deep palladium finish.',
            materials: 'Hand-selected black grained calfskin, palladium-toned hardware, tonal lambskin interior lining.',
            craft: 'Constructed by master leather artisans in the Paris atelier. Over 18 hours of precise hand-stitching and border edge burnishing.',
            sizes: ['Small (20cm)', 'Medium (25cm)', 'Jumbo (30cm)'],
            isFeatured: true,
            isNew: false
        },
        {
            id: 'handbag-02',
            slug: 'quilted-icon-concept',
            title: 'Quilted Icon — Concept',
            category: 'handbags',
            categoryLabel: 'Handbags',
            conceptTag: 'CONCEPT PIECE',
            demoPrice: 9400,
            primaryImage: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=1200&q=85',
            description: 'Sculptural silhouette celebrating the heritage of Rue Cambon. Featuring exaggerated chevron quilting, dual gusset interior, and a brushed ruthenian finish.',
            materials: 'Aged lambskin leather, brushed ruthenium metal alloy, burgundy leather lining.',
            craft: 'Individual panel quilting cut on the bias to guarantee perpetual geometric continuity across closures.',
            sizes: ['One Size (24 × 15 × 7 cm)'],
            isFeatured: true,
            isNew: true
        },
        {
            id: 'handbag-03',
            slug: 'paris-mini-digital-concept',
            title: 'Paris Mini — Digital Concept',
            category: 'handbags',
            categoryLabel: 'Handbags',
            conceptTag: 'DIGITAL CONCEPT',
            demoPrice: 5200,
            primaryImage: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',
            description: 'Compact evening volume calibrated for essential movement. Micro-chain strap, concealed magnetic closure, and hand-buffed perimeter piping.',
            materials: 'Satin-finish box calfskin, 18k pale champagne gold gilding.',
            craft: 'Single-needle topstitching performed on historical French saddlery frames.',
            sizes: ['Mini (17 × 11 × 5 cm)'],
            isFeatured: false,
            isNew: true
        },
        {
            id: 'handbag-04',
            slug: 'noir-bag-concept',
            title: 'Noir Bag — Concept',
            category: 'handbags',
            categoryLabel: 'Handbags',
            conceptTag: 'ARCHIVE CONCEPT',
            demoPrice: 7800,
            primaryImage: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',
            description: 'Radical monochrome exploration where hardware, stitching, and leather merge into a unified black absorption spectrum.',
            materials: 'Matte obsidian caviar calf, PVD black titanium hardware.',
            craft: 'Treated with an ultra-thin organic polymer shield resisting moisture while maintaining natural tactile grain.',
            sizes: ['Medium (28 × 18 × 8 cm)'],
            isFeatured: false,
            isNew: false
        },

        // ================= FOOTWEAR =================
        {
            id: 'shoe-01',
            slug: 'signature-heels-digital-concept',
            title: 'Signature Heels — Digital Concept',
            category: 'shoes',
            categoryLabel: 'Footwear',
            conceptTag: 'DIGITAL CONCEPT',
            demoPrice: 1350,
            primaryImage: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=85',
            description: 'Two-tone slingback pump with contrasting black grosgrain cap toe and beige leather body. Architectural 65mm block heel engineered for Parisian promenade comfort.',
            materials: 'Goatskin leather upper, grosgrain toe accent, hand-buffed leather sole.',
            craft: 'Lasted on custom hand-carved beechwood lasts at the Roman atelier.',
            sizes: ['EU 36', 'EU 37', 'EU 38', 'EU 39', 'EU 40', 'EU 41'],
            isFeatured: true,
            isNew: false
        },
        {
            id: 'shoe-02',
            slug: 'parisian-loafers-digital-concept',
            title: 'Parisian Loafers — Digital Concept',
            category: 'shoes',
            categoryLabel: 'Footwear',
            conceptTag: 'CONCEPT PIECE',
            demoPrice: 1450,
            primaryImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=85',
            description: 'Refined masculine-feminine balance. Polished calfskin moccasin featuring subtle hand-braided chain detail across the vamp.',
            materials: 'Glazed calf leather, memory-foam insole, stacked leather heel.',
            craft: 'Blake-stitched construction ensuring featherlight flexibility and longevity.',
            sizes: ['EU 36', 'EU 37', 'EU 38', 'EU 39', 'EU 40'],
            isFeatured: true,
            isNew: true
        },
        {
            id: 'shoe-03',
            slug: 'evening-shoes-digital-concept',
            title: 'Evening Shoes — Digital Concept',
            category: 'shoes',
            categoryLabel: 'Footwear',
            conceptTag: 'COUTURE CONCEPT',
            demoPrice: 1850,
            primaryImage: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=85',
            description: 'Slender stiletto silhouette adorned with a cluster of pavé pearls at the ankle tie. Black duchess satin upper with mirrored silver insole.',
            materials: 'Silk duchess satin, cultured freshwater pearl embroidery, calf lining.',
            craft: 'Pearls individually hand-threaded by the Lesage embroidery workshops.',
            sizes: ['EU 36', 'EU 37', 'EU 38', 'EU 39', 'EU 40'],
            isFeatured: true,
            isNew: false
        },
        {
            id: 'shoe-04',
            slug: 'couture-sneakers-digital-concept',
            title: 'Couture Sneakers — Digital Concept',
            category: 'shoes',
            categoryLabel: 'Footwear',
            conceptTag: 'MODERN CONCEPT',
            demoPrice: 1200,
            primaryImage: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=85',
            detailImage: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=85',
            description: 'Contemporary haute athletic form. Suede panels interlaid with signature woven tweed accents and sculptural bi-density sculpted soles.',
            materials: 'Velvet calfskin, Scottish tweed wool weave, natural rubber cupsole.',
            craft: 'Hybrid vulcanized and stitched outsole assembly for superior durability.',
            sizes: ['EU 36', 'EU 37', 'EU 38', 'EU 39', 'EU 40', 'EU 41'],
            isFeatured: true,
            isNew: true
        },

        // ================= FRAGRANCE =================
        {
            id: 'perfume-01',
            slug: 'no-noir-extrait-de-parfum',
            title: 'N° Noir — Extrait de Parfum',
            category: 'fragrance',
            categoryLabel: 'Fragrance',
            conceptTag: 'DIGITAL CONCEPT',
            demoPrice: 380,
            primaryImage: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1400&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1400&q=85',
            detailImage: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1400&q=85',
            description: 'An enigmatic, chiaroscuro composition. Opens with sharp aldehydes and bergamot, dissolving into May rose, Grasse jasmine, Venezuelan tonka bean, and Indonesian patchouli.',
            materials: 'Artisanal hand-blown smoky crystal flacon, baudruchage wax-sealed neck.',
            craft: 'Distilled exclusively in Grasse using field-harvested flowers picked at first dawn.',
            sizes: ['50ml Extrait', '100ml Extrait'],
            isFeatured: true,
            isNew: false
        },
        {
            id: 'perfume-02',
            slug: 'gabrielle-absolue-concept',
            title: 'Gabrielle Absolue — Concept',
            category: 'fragrance',
            categoryLabel: 'Fragrance',
            conceptTag: 'CONCEPT PIECE',
            demoPrice: 420,
            primaryImage: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1400&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1400&q=85',
            detailImage: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1400&q=85',
            description: 'A solar white floral heart composed around four points of light: exotic jasmine, ylang-ylang, sparkling orange blossom, and intensely velvety Grasse tuberose.',
            materials: 'Ultra-thin square glass flacon, martele-finished lamé stopper.',
            craft: 'Formulated with cold enfleurage captures to preserve pristine petal nuances.',
            sizes: ['50ml Eau de Parfum', '100ml Eau de Parfum'],
            isFeatured: false,
            isNew: true
        },

        // ================= HIGH JEWELRY & WATCHES =================
        {
            id: 'jewelry-01',
            slug: 'camelia-diamant-ring-concept',
            title: 'Camélia Diamant Ring — Concept',
            category: 'jewelry',
            categoryLabel: 'High Jewelry',
            conceptTag: 'HAUTE JOAILLERIE',
            demoPrice: 28500,
            primaryImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=85',
            detailImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=85',
            description: 'The geometry of Mademoiselle’s emblematic flower interpreted in 18K white gold and 142 brilliant-cut pavé diamonds with a 1.5-carat center stone.',
            materials: '18K White Gold (750/1000), F/VVS certified brilliant diamonds.',
            craft: 'Hand-set by Place Vendôme master gem-setters using micro-grain pavé technique.',
            sizes: ['EU 50', 'EU 52', 'EU 54', 'Bespoke Sizing'],
            isFeatured: true,
            isNew: false
        },
        {
            id: 'jewelry-02',
            slug: 'baroque-pearl-sautoir-concept',
            title: 'Baroque Pearl Sautoir — Digital Concept',
            category: 'jewelry',
            categoryLabel: 'High Jewelry',
            conceptTag: 'DIGITAL CONCEPT',
            demoPrice: 19800,
            primaryImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=85',
            detailImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=85',
            description: 'Long cascading multi-strand sautoir composed of graded South Sea pearls, onyx rondelles, and diamond-set double rings.',
            materials: 'Natural Australian South Sea pearls, black onyx, 18K beige gold.',
            craft: 'Knotted on hand-spun pure silk thread between each individual pearl.',
            sizes: ['Length: 95 cm'],
            isFeatured: false,
            isNew: true
        },
        {
            id: 'watch-01',
            slug: 'premiere-edition-noire-concept',
            title: 'Première Édition Noire — Concept',
            category: 'watches',
            categoryLabel: 'Horlogerie',
            conceptTag: 'HORLOGERIE CONCEPT',
            demoPrice: 14200,
            primaryImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=85',
            detailImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=85',
            description: 'Octagonal bevelled sapphire glass evocative of the Place Vendôme skyline. High-gloss black lacquer dial devoid of indices, emphasizing pure temporal silence.',
            materials: 'High-tech black ceramic, steel, black leather interwoven chain bracelet.',
            craft: 'Swiss manufacture high-precision quartz movement manufactured in La Chaux-de-Fonds.',
            sizes: ['Small (19.7 × 15.2 mm)', 'Medium (26.1 × 20 mm)'],
            isFeatured: true,
            isNew: false
        },

        // ================= READY-TO-WEAR & COUTURE =================
        {
            id: 'fashion-01',
            slug: 'tweed-tailleur-parisien',
            title: 'Tweed Tailleur Parisien — Concept',
            category: 'fashion',
            categoryLabel: 'Haute Couture',
            conceptTag: 'HAUTE COUTURE',
            demoPrice: 12500,
            primaryImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1600&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1600&q=85',
            detailImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
            description: 'The definitive architectural jacket. Boxy silhouette, three-quarter raglan sleeves, braided wool galloon trim, and interior brass hem chain ensuring impeccable drape.',
            materials: 'Lesage bespoke wool and silk boucle tweed, camellia silk jacquard lining.',
            craft: 'Over 130 hours of hand-cutting, basting, fitting, and finishing in the Rue Cambon tailoring ateliers.',
            sizes: ['FR 34', 'FR 36', 'FR 38', 'FR 40', 'FR 42'],
            isFeatured: true,
            isNew: true
        },
        {
            id: 'fashion-02',
            slug: 'soie-noire-evening-cape',
            title: 'Soie Noire Evening Cape — Concept',
            category: 'fashion',
            categoryLabel: 'Haute Couture',
            conceptTag: 'DIGITAL CONCEPT',
            demoPrice: 11200,
            primaryImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1600&q=85',
            secondaryImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1600&q=85',
            detailImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
            description: 'Dramatic floor-length evening cape in heavy double silk georgette with high standing collar and hidden pearl button fastenings.',
            materials: '100% Lyon mulberry silk georgette, silk organza underlining.',
            craft: 'Draped on the Rue Cambon atelier form using single bias cutting.',
            sizes: ['FR 36', 'FR 38', 'FR 40'],
            isFeatured: false,
            isNew: false
        }
    ];

    const MenuCategories = [
        { key: 'fashion', label: 'Fashion', image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=fashion' },
        { key: 'handbags', label: 'Handbags', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=handbags' },
        { key: 'shoes', label: 'Shoes', image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=shoes' },
        { key: 'jewelry', label: 'Jewelry', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=jewelry' },
        { key: 'watches', label: 'Watches', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=watches' },
        { key: 'beauty', label: 'Beauty', image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=beauty' },
        { key: 'fragrance', label: 'Fragrance', image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1200&q=85', url: 'shop.html?cat=fragrance' },
        { key: 'couture', label: 'Couture', image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85', url: 'collection.html' },
        { key: 'house', label: 'The House', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85', url: 'about.html' }
    ];

    window.ProductsData = PRODUCTS_DATA;
    window.MenuCategories = MenuCategories;
})(window);
